"""
Generates the per-object `<object>_asset_map.txt` JSON files that
Object_Selection.load_asset_map() expects.

The SLIPPAGE_THRESHOLDS are not invented -- they are derived from the recorded
training data by replaying the exact metric the monitoring loop uses:

    max_delta = max( |smoothed_current - baseline| / baseline )

with the same 10-sample initial baseline and the same EMA baseline update
(0.9/0.1). We measure the distribution of that metric across all HEALTHY grips
(good_grip + semi_good_grip) and place the thresholds above its upper
percentiles, so a stable healthy grip does not trip them:

    WARNING  = p90 of healthy   -> 10% of healthy samples exceed it
    CRITICAL = p99 of healthy   ->  1% of healthy samples exceed it
    ABORT    = max of healthy   -> no healthy sample seen exceeded it

Combined with CONSECUTIVE_HITS debouncing, this keeps false alarms low while
still reacting to genuine departures from the established baseline.

Run:  python3 Make_Asset_Configs.py --data-dir <dir> --out-dir <dir>
"""

import os
import json
import argparse
import numpy as np
from collections import deque

from Data_Loader import build_dataset, SENSOR_COLS, GRIP_CATEGORIES

SMOOTHING_WINDOW = 10   # samples; see README for the noise analysis
EMA_ALPHA = 0.9


def healthy_delta_distribution(df, win=SMOOTHING_WINDOW, ema=EMA_ALPHA):
    """Replay the monitoring metric over all healthy-grip recordings."""
    healthy = df[df.grip_label.isin(['good_grip', 'semi_good_grip'])]
    out = []
    for _, g in healthy.groupby('source_file'):
        v = g[SENSOR_COLS].values.astype(float)
        if len(v) < win + 10:
            continue
        base = v[:10].mean(axis=0)
        buf = deque(maxlen=win)
        for row in v[10:]:
            buf.append(row)
            cur = np.mean(buf, axis=0)
            out.append((np.abs(cur - base) / (base + 1e-6)).max())
            base = base * ema + cur * (1.0 - ema)
    return np.array(out)


def build_config(dataset, model_path, scaler_path, df, is_fragile=False):
    d = healthy_delta_distribution(df)
    warn = float(np.percentile(d, 90))
    crit = float(np.percentile(d, 99))
    abort = float(d.max())

    return {
        "_comment": (
            f"Auto-generated by Make_Asset_Configs.py for the '{dataset}' object. "
            f"Slippage thresholds derived from {len(d)} healthy-grip samples."
        ),
        "MODEL_PATH": model_path,
        "SCALER_PATH": scaler_path,
        "CATEGORIES": GRIP_CATEGORIES,
        "IS_FRAGILE": bool(is_fragile),

        "SLIPPAGE_THRESHOLDS": {
            "WARNING": round(warn, 3),
            "CRITICAL": round(crit, 3),
            "ABORT": round(abort, 3),
        },

        "QUALITY_THRESHOLDS": {
            # Confidence floors before an NN prediction triggers an action.
            # no_grip is classified perfectly on both objects (F1 = 1.00) and
            # its predictions are high-confidence, so a high bar is safe and
            # avoids acting on a single noisy frame.
            "NO_GRIP_CRITICAL_CONF": 0.90,
            # bad_grip is the weakest class (F1 0.83 sponge / 0.73 holder), so
            # this bar is deliberately lower -- raising it would suppress real
            # detections, lowering it would act on unreliable predictions.
            "BAD_GRIP_WARNING_CONF": 0.60,
        },

        # --- Monitoring-loop behaviour (added; see README) ---
        "SMOOTHING_WINDOW": SMOOTHING_WINDOW,
        "EMA_ALPHA": EMA_ALPHA,
        "CONSECUTIVE_HITS": 3,     # set to 1 to restore original un-debounced behaviour
        "MAX_MONITOR_CYCLES": 5000,

        "_threshold_provenance": {
            "healthy_samples_analysed": int(len(d)),
            "healthy_median": round(float(np.median(d)), 3),
            "healthy_p90": round(warn, 3),
            "healthy_p99": round(crit, 3),
            "healthy_max": round(abort, 3),
            "metric": "max(|smoothed_current - ema_baseline| / ema_baseline)",
        },
    }


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--data-dir', default='data')
    ap.add_argument('--out-dir', default='configs')
    ap.add_argument('--model-dir', default='.')
    args = ap.parse_args()

    os.makedirs(args.out_dir, exist_ok=True)

    for dataset in ('sponge', 'holder'):
        df = build_dataset(args.data_dir, dataset=dataset, verbose=False)
        cfg = build_config(
            dataset,
            os.path.join(args.model_dir, f'one_phase_nn_grip_model_{dataset}.keras'),
            os.path.join(args.model_dir, f'one_phase_nn_{dataset}_scaler.joblib'),
            df,
        )
        path = os.path.join(args.out_dir, f'{dataset}_asset_map.txt')
        with open(path, 'w') as f:
            json.dump(cfg, f, indent=2)
        st = cfg['SLIPPAGE_THRESHOLDS']
        print(f"{dataset:<8} -> {path}")
        print(f"          WARNING={st['WARNING']}  CRITICAL={st['CRITICAL']}  ABORT={st['ABORT']}"
              f"   (from {cfg['_threshold_provenance']['healthy_samples_analysed']} healthy samples)")


if __name__ == '__main__':
    main()
